---
title: "Untitled"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(reshape2)
library(stringr)
```

```{r, cache=TRUE}
weather_events <- read.csv("StormData.csv")
```

```{r, cache=TRUE}
weather_events$EVTYPE <- 
  gsub("^TORN.*", "TORNADO", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub("^THUNDER.*TORM.*", "THUNDERSTORM WINDS", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub("^TSTM WIND.*", "THUNDERSTORM WINDS", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub("^FLOOD.*", "FLOOD", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub("^LIGHTNING.*", "LIGHTNING", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub(".*ICE STORM.*", "ICE STORM", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub("^WINTER STORM.*", "WINTER STORM", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub("^HIGH WIND.*", "HIGH WINDS", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub("^HURRICANE.*", "HURRICANE", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub("^WILD.*FIRE.*", "WILDFIRE", weather_events$EVTYPE)
weather_events$EVTYPE <- 
  gsub(".*FOG.*", "FOG", weather_events$EVTYPE)

convert_multiplier <- function(mult) {
  if (mult %in% c("k", "K")) {
    return(1000)
  } else if(mult %in% c("m", "M")) {
    return(1000000)
  } else if (mult %in% c("b", "B")) {
    return(1000000000)
  } else {
    return(0)
  }
}

weather_events$PROPDMGMULT <- 
  sapply(weather_events$PROPDMGEXP, convert_multiplier)
weather_events$CROPDMGMULT <- 
  sapply(weather_events$CROPDMGEXP, convert_multiplier)
weather_events <- weather_events %>% 
  mutate(PROPDMG = PROPDMG * PROPDMGMULT, CROPDMG = CROPDMG * CROPDMGMULT)
```

## Casualties ##

```{r, fig.width=12, fig.height=6}
worst_casualty_events <- weather_events %>%
  filter(FATALITIES > 0 | INJURIES > 0) %>%
  group_by(EVTYPE) %>%
  summarize(TOTAL_CASUALTIES = sum(FATALITIES + INJURIES), 
            TOTAL_FATALITIES = sum(FATALITIES),
            TOTAL_INJURIES = sum(INJURIES)) %>%
  arrange(desc(TOTAL_CASUALTIES))

top_n <- 15
sp <- split(worst_casualty_events, 
            c(rep(0, top_n), rep(2, nrow(worst_casualty_events) - top_n)))

top_worst_events <- sp[[1]]
other_worst_events <- sp[[2]] %>%
  mutate(EVTYPE="OTHER") %>%
  group_by(EVTYPE) %>%
  summarize(TOTAL_CASUALTIES = sum(TOTAL_CASUALTIES), 
            TOTAL_FATALITIES = sum(TOTAL_FATALITIES),
            TOTAL_INJURIES = sum(TOTAL_INJURIES))
  
worst_events_summary <- rbind(top_worst_events, other_worst_events)
worst_events_summary$EVTYPE <- str_wrap(worst_events_summary$EVTYPE, width=10)
worst_events_summary$EVTYPE <- 
  factor(worst_events_summary$EVTYPE, levels=worst_events_summary$EVTYPE)

molten_events <- melt(
  select(worst_events_summary, EVTYPE, TOTAL_FATALITIES, TOTAL_INJURIES), 
  id=c("EVTYPE"))
molten_events$variable <- 
  factor(molten_events$variable, 
         levels=c("TOTAL_FATALITIES", "TOTAL_INJURIES"), 
         labels=c("fatalities", "injuries"))

ggplot(molten_events, aes(EVTYPE, value, fill = variable)) +
  geom_bar(stat = "identity") +
  xlab("") + 
  ylab("casualties") +
  theme(axis.text.x = element_text(angle=45, vjust=0.5)) 
```

## Damage ##
```{r, fig.width=12, fig.height=6}
worst_damage_events <- weather_events %>%
  group_by(EVTYPE) %>%
  summarize(TOTAL_DAMAGE = sum(PROPDMG + CROPDMG) / 10^9, 
            TOTAL_PROPERTY_DAMAGE = sum(PROPDMG) / 10^9,
            TOTAL_CROP_DAMAGE = sum(CROPDMG) / 10^9) %>%
  arrange(desc(TOTAL_DAMAGE))

top_n <- 15
sp <- split(worst_damage_events, 
            c(rep(0, top_n), rep(2, nrow(worst_damage_events) - top_n)))

top_worst_events <- sp[[1]]
other_worst_events <- sp[[2]] %>%
  mutate(EVTYPE="OTHER") %>%
  group_by(EVTYPE) %>%
  summarize(TOTAL_DAMAGE = sum(TOTAL_DAMAGE), 
            TOTAL_PROPERTY_DAMAGE = sum(TOTAL_PROPERTY_DAMAGE),
            TOTAL_CROP_DAMAGE = sum(TOTAL_CROP_DAMAGE))

worst_events_summary <- rbind(top_worst_events, other_worst_events)
worst_events_summary$EVTYPE <- str_wrap(worst_events_summary$EVTYPE, width=10)
worst_events_summary$EVTYPE <- 
  factor(worst_events_summary$EVTYPE, levels=worst_events_summary$EVTYPE)

molten_events <- melt(
  select(worst_events_summary, 
         EVTYPE, TOTAL_PROPERTY_DAMAGE, TOTAL_CROP_DAMAGE), 
  id=c("EVTYPE"))
molten_events$variable <- 
  factor(molten_events$variable, 
         levels=c("TOTAL_PROPERTY_DAMAGE", "TOTAL_CROP_DAMAGE"), 
         labels=c("property", "crop"))

ggplot(molten_events, aes(EVTYPE, value, fill = variable)) +
  geom_bar(stat = "identity") +
  xlab("") + 
  ylab("damage (billions)") +
  theme(axis.text.x = element_text(angle=45, vjust=0.5)) 
```